single task. Single user page
htmlacademy-yii/1865271-task-force-2 pull request #14
Opened 2022-03-12 14:38 UTC by ipodzem

Созданы action'ы: tasks/view users/view

Добавлена миграция для добавления поля score для users (Чтобы не рассчитывать его при каждом обращении, думаю сохранять после добавления отзыва)

Вопросы:
1. Нормальна ли реализация хелпера для рейтинга или лучше какой-то виджет создавать?
2. Не работает return Yii::t('app','{delta, plural, 0 {нет отзывов} one{# отзыв} few{# отзыва} many{# отзывов} other{# отзывов}}', ['delta' => count($this->ratings)]);
Не могу найти причину
3. <?php foreach($model->ratings as $rating) {
       echo $this->render('_feedback', ['model' => $rating]);
    }?>

2022-03-12 14:39 UTC, ipodzem commented
3. <?php foreach($model->ratings as $rating) {
       echo $this->render('_feedback', ['model' => $rating]);
    }?>
Такая реализация нормальна или надо через listview?

2022-03-13 13:18 UTC, sterlikoff requested changes
Ирина, очень хорошо, почти все получилось! Наведем немного порядок и будет отлично:

1. При попытке просмотреть задание ошибка:
`Non-static method app\components\CustomHelper::drawScore() cannot be called statically`

 - Метод действительно не статичный, а вызывается статично.

 - Здесь же, если есть необходимость собирать PHP-кодом какую то разметку, лучше использовать свойства `tag`, `beginTag` и `endTag` Yii-класса `Html`.

 - Более подходящее название все же `render` вместо `draw`.

 - Пытаешься выводить результат вызова:
`echo CustomHelper::drawScore($model->user->score)`. Но `drawScore` ничего не возвращает, а значит ничего и не выведет.

2. Используй phpDoc в начале  представлений, чтобы не было вот таких ситуаций:
http://joxi.ru/brRaXd0H7x9y6A

3. Вместо `foreach` в представлениях следует использовать виджеты, например `ListView`

4. Вот тут давай сразу сделаем ссылку на профиль исполнителя: http://joxi.ru/eAOL35gu9OBwZr

5. у `safeDown` в миграциях не надо ничего возвращать

6. закомментированные части кода и неиспользуемые `use` убираем везде :)

2022-03-15 05:52 UTC, ipodzem commented
Поправила.
Вопрос остался с "Не работает return Yii::t('app','{delta, plural, 0 {нет отзывов} one{# отзыв} few{# отзыва} many{# отзывов} other{# отзывов}}', ['delta' => count($this->ratings)]);"

2022-03-15 07:50 UTC, sterlikoff approved these changes
Ирина, супер, все поправила, что я просил.

Еще моменты:

- На вопрос про звездочки рейтинга. Вообще это спорно и вкусовщина :) Но практика такая, когда начинаешь делать всякие `CustomHelper`, они в итоге разрастаются в монстров, в которых чего только нет, а это уже не очень хорошо. Если сделаешь виджетом, будет очень хорошо!

- Про `Yii::t` и `plural` - для того, чтобы это сработало нужно: 1) установить расширение PHP intl 2) в конфигурации приложения указать `'sourceLanguage' => 'ru-RU'`. А саму конструкцию составила верно :)

- Давай еще метод `getRatingsCnt` переименуем в `getRatingsCountLabel`. Сокращения в названиях лучше не использовать, и метод возвращает все-таки не просто количество, а отформатированную строку.

Для зачета тут достаточно, можно подправить это в рамках следующего задания.

2022-03-15 07:51 UTC, merged