Registration page
htmlacademy-yii/1865271-task-force-2 pull request #15
Opened 2022-03-22 08:18 UTC by ipodzem

Добавлен контроллер RegistrationController и соответствующая форма

2022-03-22 08:19 UTC, ipodzem commented
Не уверена, зачем нужна галочка  "я собираюсь откликаться на заказы" - сохранить ее в базе или использовать для определения типа пользователя?

2022-03-22 16:57 UTC, sterlikoff requested changes
Ирина, все очень неплохо, немного еще поработаем над кодом:

1. В контроллере много "мусора" видимо после копирования с `SiteController`:

- http://joxi.ru/82QZnWGSwXQGMA
- http://joxi.ru/Q2K5Kj8uLZV8lr
- http://joxi.ru/52a5jJ3uEpVyp2
- http://joxi.ru/82397gDf91NBvr

2. Текущий запрос в методах контроллеров доступен через `$this`:

`Yii::$app->request->getIsPost()` -> `$this->request->isPost`

3. Для регистрации лучше создать отдельную форму `extends yii\base\Model`, чтобы отделить логику от `ActiveRecord`-модели `User`. 

4. Напрямую в `$_POST` не смотрим, мы же перед этим загрузили модель, значит `responsible` есть у `model`. 

5. Старайся везде использовать строгие сравнения:
`$post['User']['responsible'] == 1`

Хотя конкретно это нужно реализовать в `rules()` модели.

6. Некорректный phpDoc:
`/* @var $model app/models/User;*/`

Для массивов можно указывать точные типы:
`/* @var City[] $cities */`

7. Повтор пароля не обязательный:
http://joxi.ru/L21913DfRl7o52

Ни визуально не видно валидации, ни на бэкенде - форма срабавает и без него.

8. Если я сохраню не новую модель, посчитается хэш-сумма от хэш-суммы и пароль будет утерян:

```
        if (isset($this->password))
            $this->password = Yii::$app->getSecurity()->generatePasswordHash($this->password);
```

На твой вопрос про галочку - да, в зависимости от нее выбираем роль - верно поняла.

2022-03-26 16:11 UTC, sterlikoff requested changes
Ирина, по прошлым замечаниям все хорошо теперь, но появились еще некоторые моменты :)

1. Все еще есть какие то рудименты: http://joxi.ru/82397gDf91ZNvr http://joxi.ru/ZrJQLE7swKaqvA
2. Тут как то сложно получилось:
```
   if ($res['success'] == true) {
                    return $this->redirect('/');
                } else {
                    \Yii::$app->session->setFlash(
                        'error',
                        $res['msg']
                    );
                }
```

Тут вполне четко все: если форма сработала успешно - редирект, если нет - рендер и ошибки пользователь смотрит на представлении. Flash в этом случае не нужен.

Соответственно, `register` может просто `bool` возвращать.

3. `$user->validate() && $user->save()` можно заменить на просто `$user->save()`, так как `save` у `ActiveRecord` вызывает перед своими операциями валидацию и не сохранит модель, если с ней что-то не так.

4. `TaskService::TYPE_EXECUTOR` -> `TaskInterface::TYPE_EXECUTOR`, так как константы объявлены в интерфейсе. Это не страшно, но немного некорректно.

5. Хочется, чтобы ошибка некорректного email'а тоже отображалась как и все, под соответствующим полем: http://joxi.ru/J2b6pJOs0z3jJ2. Наверняка 2 пункт решит эту проблему, но обрати внимание.

2022-03-29 07:34 UTC, sterlikoff approved these changes
Ирина, отлично, все работает, код хороший :)

Маленький момент: ` $user->load($this->attributes, '');`
Все же лучше здесь расписать подробно каждый атрибут. Правила валидации могут поменяться в `User` и мы может забыть учесть это в `RegistrationForm`.

2022-03-29 07:34 UTC, merged