Module2 task2
htmlacademy-yii/1865271-task-force-2 pull request #6
Opened 2022-01-19 04:01 UTC by ipodzem

Добавлены классы-действия папка src/services
Добавлены проверки в файл test.php

2022-01-19 16:40 UTC, sterlikoff requested changes
Ирина, здорово, Action'ы и абстракция к ним реализованы верно. Разве что можно добавить типизацию функций, чтобы функции возвращали однозначный тип в соответствии с возможностями PHP7-8. Например `public function getName(): string`, и т.д.

Над чем еще надо поработать:

1. Надо уйти от констант вида `ACTION_*`, их должно не стать совсем. 

2. `getActionMap` должен теперь возвращать массив с TaskAction'ами, т.е. не `[Task::ACTION_CANCEL => new CancelAction]`, а просто `new CancelAction`

3. `TaskAction` лучше назвать `AbstractAction`, по названию абстракций должно быть понятно, что это абстракция, с ними так будет легче работать.

4. Функция `getActionName` не нужна, мы теперь можем у Action'а сразу обратиться к `getName()`.

4. Переписать тесты в соответствии с этими изменениями.

2022-01-21 00:58 UTC, ipodzem commented
Спасибо!
Отправила изменения. Меня немного смущает реализация
getActionMap, которая теперь не учитывает запрашиваемый action. Сейчас по заданию одномерный массив, но если вдруг  для статуса NEW и для типа пользователя CUSTOMER будет несколько actions?

2022-01-21 14:46 UTC, sterlikoff requested changes
Ирина, отлично, осталось чуть-чуть:

1. В `getActionMap` возвращаемый тип будет не `object`, а `AbstractAction`. Кстати в случаях, когда нужно обозначить неизвестный объект, в php используется не `object`, а `stdClass`. Ну это так, к слову) Мы должны стараться писать код так, чтобы таких случаев не было)

2. Что касается твоего вопроса, о том, что Action'ов может быть несколько, кажется таких ситуаций нет в этом проекте. Но в принципе ничего не мешает нам возвращать массив Action'ов. Но в этом случае мы должны будем учесть это всюду, где используется `getActionMap`, например в `checkAction` перебирать все доступные Action'ы.

3. `getInnerName` нам больше не нужны в Action'ах, да и они вызывают ошибку - используемые в них константы мы удалили.

4. В assert'ах можно не использовать сравнение с true:
`$task->checkAction(Task::STATUS_NEW, Task::TYPE_CUSTOMER, 1) == true` -> `$task->checkAction(Task::STATUS_NEW, Task::TYPE_CUSTOMER, 1)`

`assert` сам это делает, причем с помощью строгого сравнения `===`

2022-01-26 15:27 UTC, sterlikoff approved these changes
Ирина, теперь все отлично :) Зачет!

2022-01-26 15:27 UTC, merged